Repository SAKPaaS/frontend, pull requests merged in 2020-04, with the labels that each got.

#102 Feature/add config for api endpoint
  SAKPaaS/openapi.yaml
  SAKPaaS/src/app/app.module.ts
  SAKPaaS/src/app/config-loader.ts
  SAKPaaS/src/app/generated/api-configuration.ts
Labels: enhancement

#140 TINF-193: Added Automatic Tests
  .github/workflows/test.yaml
  SAKPaaS/package.json
  SAKPaaS/src/app/app.module.ts
  SAKPaaS/src/app/core/services/pwa-request-catcher.service.ts
Labels: enhancement, important

#141 TINF-XX: Fixed typos
  .github/workflows/integration.yaml
  .github/workflows/tests.yaml
Labels: bug

#142 Feature/tinf 32 open api yaml ins frontend einbinden
  SAKPaaS/openapi.yaml
  SAKPaaS/package-lock.json
  SAKPaaS/package.json
  SAKPaaS/src/app/generated/api-configuration.ts
  SAKPaaS/src/app/generated/api.module.ts
  SAKPaaS/src/app/generated/models.ts
  SAKPaaS/src/app/generated/models/location-search-result.ts
  SAKPaaS/src/app/generated/request-builder.ts
  SAKPaaS/src/app/generated/services/locations.service.ts
Labels: important

#143 Feature/tinf 199 wenn report abgegeben wird aktualisieren die locations nicht
  SAKPaaS/src/app/components/map/map.component.ts
  SAKPaaS/src/app/core/services/location-provider.service.ts
  SAKPaaS/tslint.json
Labels: bug

#148 TINF 194 PWA Installation Prompt
  SAKPaaS/src/app/app.component.ts
  SAKPaaS/src/app/components/occupancy-report/occupancy-report.component.ts
  SAKPaaS/src/app/core/services/pwa-request-catcher.service.ts
  SAKPaaS/src/app/core/services/pwa-request-prompt.service.spec.ts
  SAKPaaS/src/app/core/services/pwa-request-prompt.service.ts
Labels: bug, frontend

#154 TINF-198 installation prompt fixedc
  SAKPaaS/src/app/app.component.ts
  SAKPaaS/src/app/core/services/pwa-request-catcher.service.ts
  SAKPaaS/src/app/core/services/pwa-request-prompt.service.ts
Labels: bug, frontend

#151 Feature/tinf 79 dialog checkboxes dsgvo standort
  SAKPaaS/src/app/app.module.ts
  SAKPaaS/src/app/components/global-dialog/global-dialog.component.html
  SAKPaaS/src/app/components/global-dialog/global-dialog.component.ts
  SAKPaaS/src/app/core/models/checkboxes-dialog.interface.ts
  SAKPaaS/src/app/core/models/dialog-message.interface.ts
  SAKPaaS/src/app/core/services/map.service.ts
  SAKPaaS/src/app/shared/shared.module.ts
  SAKPaaS/src/assets/i18n/de.json
  SAKPaaS/src/assets/i18n/en.json
Labels: frontend

#155 [Bugfix] TINF-232 Standortfrage und Cookies werden vom Browser direkt gemacht
  SAKPaaS/src/app/app.component.ts
  SAKPaaS/src/app/core/services/cookie-provider.service.ts
  SAKPaaS/src/app/core/services/map.service.ts
  SAKPaaS/src/app/core/services/mixpanel.service.ts
  SAKPaaS/src/app/core/services/permissions.service.spec.ts
  SAKPaaS/src/app/core/services/permissions.service.ts
  SAKPaaS/src/index.html
Labels: bug

#178 [Feature] TINF-317 Hintergrund wird dunkel
  SAKPaaS/src/app/components/home/home.component.html
  SAKPaaS/src/app/components/home/home.component.scss
  SAKPaaS/src/app/components/home/home.component.ts
  SAKPaaS/src/app/components/user-card/user-card.component.scss
  SAKPaaS/src/app/components/user-card/user-card.component.ts
  SAKPaaS/src/app/core/services/background-blur.service.spec.ts
  SAKPaaS/src/app/core/services/background-blur.service.ts
Labels: frontend

#177 Feature/tinf 277 badge ansicht
  SAKPaaS/package-lock.json
  SAKPaaS/src/app/components/user-card/user-card.component.html
  SAKPaaS/src/app/components/user-card/user-card.component.scss
  SAKPaaS/src/app/components/user-card/user-card.component.ts
  SAKPaaS/src/app/components/user-card/user-card.module.ts
  SAKPaaS/src/app/core/models/badge.interface.ts
  SAKPaaS/src/assets/badges/locked.png
  SAKPaaS/src/assets/badges/new_report.png
  SAKPaaS/src/assets/badges/next_level.png
  SAKPaaS/src/assets/badges/next_level_class.png
  SAKPaaS/src/assets/badges/report.png
  SAKPaaS/src/assets/badges/shop_first_report.png
  SAKPaaS/src/assets/badges/trusted_shop.png
  SAKPaaS/src/assets/badges/trusted_user.png
  SAKPaaS/src/assets/badges/two_shops.png
  SAKPaaS/src/assets/badges/week_1.png
  SAKPaaS/src/assets/badges/week_3.png
  SAKPaaS/src/assets/badges/week_full.png
  SAKPaaS/src/assets/badges/week_special.png
  SAKPaaS/src/assets/i18n/de.json
  SAKPaaS/src/assets/i18n/en.json
Labels: frontend
