Repository SAKPaaS/frontend, pull requests merged in 2020-03, with the labels that each got.

#8 #3: Feature/location details
  SAKPaaS/src/app/app.module.ts
  SAKPaaS/src/app/components/home/home.component.html
  SAKPaaS/src/app/components/home/home.component.ts
  SAKPaaS/src/app/components/location-details/location-details.component.html
  SAKPaaS/src/app/components/location-details/location-details.component.scss
  SAKPaaS/src/app/components/location-details/location-details.component.ts
  SAKPaaS/src/styles.scss
Labels: frontend

#56 Fixed http to https rewrite more permanently
  Dockerfile
  SAKPaaS/src/app/app.component.ts
  docker/nginx.conf
Labels: cleancode

#64 Fixed bug in location provider
  SAKPaaS/src/app/components/map/map.component.ts
  SAKPaaS/src/app/core/services/location-provider.service.ts
Labels: bug

#76 Added GitHub-Action workflows
  .github/workflows/development.yaml
  .github/workflows/dockerimage.yml
  .github/workflows/release.yml
  Dockerfile
  SAKPaaS/package-lock.json
  SAKPaaS/package.json
  SAKPaaS/src/app/app.component.ts
  SAKPaaS/src/app/components/home/home.component.ts
  SAKPaaS/src/app/components/locate-button/locate-button.component.ts
  SAKPaaS/src/app/components/occupancy-view/occupancy-view.component.ts
  SAKPaaS/src/app/components/search-bar/search-bar.component.ts
  SAKPaaS/src/app/components/snack-bar/snack-bar.component.ts
  SAKPaaS/tslint.json
Labels: enhancement

#91 Fixed old workflows
  .github/workflows/development.yaml
  .github/workflows/release.yml
Labels: bug

#93 Changed redirect domain
  docker/nginx.conf
Labels: bug
