Repository SAKPaaS/frontend, pull requests merged in 2020-05, with the labels that each got.

#188 TINF-322 | Apply mobile design to home component
  SAKPaaS/package-lock.json
  SAKPaaS/src/app/components/footer/footer.component.scss
  SAKPaaS/src/app/components/home/home.component.html
  SAKPaaS/src/app/components/home/home.component.scss
  SAKPaaS/src/app/components/home/home.component.ts
  SAKPaaS/src/app/components/location-panel/location-panel.component.html
  SAKPaaS/src/app/components/location-panel/location-panel.component.scss
  SAKPaaS/src/app/components/location-panel/location-panel.component.ts
  SAKPaaS/src/app/components/location-panel/location-panel.module.ts
  SAKPaaS/src/app/components/map/map.component.html
  SAKPaaS/src/app/components/map/map.component.scss
  SAKPaaS/src/app/components/map/map.component.ts
  SAKPaaS/src/app/components/search-bar/search-bar.component.scss
  SAKPaaS/src/app/components/search-bar/search-bar.component.ts
Labels: frontend

#196 TINF-382 | Fix map for transition
  SAKPaaS/package-lock.json
  SAKPaaS/package.json
  SAKPaaS/src/app/app.module.ts
  SAKPaaS/src/app/components/map/map.component.ts
Labels: frontend

#198 Feature/tinf 385 abstand zur tatsachlichen position
  SAKPaaS/package-lock.json
  SAKPaaS/src/app/components/location-card/location-card.component.html
  SAKPaaS/src/app/components/location-card/location-card.component.ts
  SAKPaaS/src/app/components/location-list/location-list.component.ts
  SAKPaaS/src/app/core/pipes/readable-distance.pipe.ts
  SAKPaaS/src/app/core/services/gps.service.ts
  SAKPaaS/src/app/core/services/location-provider.service.ts
  SAKPaaS/src/app/shared/shared.module.ts
Labels: frontend

#193 Feature/tinf 323 user card mobile ansicht
  SAKPaaS/src/app/components/home/home.component.ts
  SAKPaaS/src/app/components/sidenav/sidenav.component.html
  SAKPaaS/src/app/components/user-card/user-card.component.html
  SAKPaaS/src/app/components/user-card/user-card.component.scss
  SAKPaaS/src/app/components/user-card/user-card.component.spec.ts
  SAKPaaS/src/app/components/user-card/user-card.component.ts
Labels: frontend

#199 Feature/tinf 387 suchergebnisse nach abstand sortieren
  SAKPaaS/src/app/components/location-card/location-card.component.scss
  SAKPaaS/src/app/components/location-card/location-card.component.ts
  SAKPaaS/src/app/components/location-list/location-list.component.ts
  SAKPaaS/src/app/core/pipes/readable-distance.pipe.ts
  SAKPaaS/src/app/core/services/location-provider.service.ts
  SAKPaaS/src/app/shared/shared.module.ts
Labels: frontend

#213 fixed missing translations
  SAKPaaS/src/app/components/user-card/user-card.component.html
  SAKPaaS/src/app/components/user-card/user-card.component.ts
Labels: bug

#209 TINF-414: Adding x for deletion to search bar
  SAKPaaS/src/app/components/search-bar/search-bar.component.html
  SAKPaaS/src/app/components/search-bar/search-bar.component.scss
  SAKPaaS/src/app/components/search-bar/search-bar.component.ts
Labels: enhancement, frontend
